### ISSUE TITLE
[Bug] Unable to install  and bulid the plugin in macos

### ISSUE THREAD

**Issue by yiakwy** [vowstar/gitbook-plugin-uml#11]
When I first typed

> gitbook install

I got 

```
➜  pedia git:(refactor_tmp) ✗ gitbook install
info: installing 4 plugins using npm@3.9.2 
info:  
info: installing plugin "uml" 
info: install plugin "uml" (*) from NPM with version 1.0.1 
internal/child_process.js:345
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:345:11)
    at exports.spawn (child_process.js:521:9)
    at spawn (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/spawn.js:7:13)
    at runCmd_ (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:237:14)
    at runCmd (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:196:5)
    at runPackageLifecycle (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:160:3)
    at Array.<anonymous> (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at chain (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
    at lifecycle_ (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:131:3)
```

after I triggered the command the second time, the error gone. However I got another eror when build pages:

> gitbook build ./ --log=debug --debug

```
➜  pedia git:(refactor_tmp) ✗ gitbook build ./ --log=debug --debug
debug: readme found at README.md 
debug: summary file found at SUMMARY.md 
debug: cleanup folder "/Users/lei.wang1/Github/mold/pedia/_book" 
info: 11 plugins are installed 
info: 10 explicitly listed 
info: loading plugin "uml"... ERROR

PluginError: Error with plugin "uml": Cannot find module 'safe-buffer'
PluginError: Error with plugin "uml": Cannot find module 'safe-buffer'
    at createError (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/error/typed.js:31:22)
    at new createError (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/error/wrapped.js:88:19)
    at /Users/lei.wang1/.gitbook/versions/3.2.3/lib/plugins/loadPlugin.js:67:23
    at _fulfilled (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/q/q.js:834:54)
    at /Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/q/q.js:796:13)
    at /Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/q/q.js:857:14
    at runSingle (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/q/q.js:137:13)
    at flush (/Users/lei.wang1/.gitbook/versions/3.2.3/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:172:11)
```

Here my gitbook version:

```
➜  pedia git:(refactor_tmp) ✗ gitbook --version
CLI version: 2.3.0
GitBook version: 3.2.3

MacOS latest
Node latest
```

The uml is v 1.0.1

**Comment by vowstar** [comment]
npm@3.9.2 is too old

```bash
pedia git:(refactor_tmp) ✗ gitbook install
info: installing 4 plugins using npm@3.9.2 
```

Please upgrade your nodejs and npm
```bash
$ npm -v
6.4.1
$ node -v
v10.15.1
```
